### ISSUE TITLE
add a link to lead to the corresponding page for every image

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api-webshots#4]
probably just along side with timing (e.g. `t=0.55`) add a `Go to page` link which would go to that page

**Comment by jwodder** [comment]
@yarikoptic So you want `info.yaml` to look something like:

```yaml
times:  
  landing: 0.5529872188344598
  view-data: 0.5527967950329185
links:
  landing: https://gui-beta-dandiarchive-org.netlify.app/#/dandiset/000027
  view-data: https://gui-beta-dandiarchive-org.netlify.app/#/dandiset/000027/draft/files
```

Is that what you're asking for?
